apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "cac.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/client-max-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    {{- include "cac.labels" . | nindent 4 }}
spec:
   tls:
   - hosts:
     - cac-management.cn.blockchain.thoughtworks.cn
     secretName: {{ include "cac.fullname" . }}-tls
  rules:
    - host: cac-management.cn.blockchain.thoughtworks.cn
      http:
        paths:
          - backend:
              serviceName: {{ include "cac.fullname" . }}
              servicePort: 8080
