apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "big-screen.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/client-max-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    {{- include "big-screen.labels" . | nindent 4 }}
spec:
  # tls:
  # - hosts:
  #   - cac-management.cn.blockchain.thoughtworks.cn
  #   secretName: {{ include "big-screen.fullname" . }}-tls
  rules:
    - host: cac-management.cn.blockchain.thoughtworks.cn
      http:
        paths:
          - backend:
              serviceName: {{ include "big-screen.fullname" . }}
              servicePort: 80
