apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "big-screen.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/client-max-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
  labels:
    {{- include "big-screen.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.cac.host }}
      http:
        paths:
          - backend:
              serviceName: {{ include "big-screen.fullname" . }}
              servicePort: http
            path: /admin/