apiVersion: v1
kind: Service
metadata:
  name: {{ include "big-screen.fullname" . }}
  labels:
    {{- include "big-screen.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    {{- include "big-screen.selectorLabels" . | nindent 4 }}
