name: CI

on:
  push:
    branches: [ "feature/irita" ]
  pull_request:
    branches: [ "feature/irita" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
